# Generated by Django 5.2.9 on 2026-02-27 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('display_name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField()),
                ('city', models.CharField()),
                ('dob', models.DateField()),
                ('password', models.CharField()),
                ('image', models.ImageField(upload_to='images/profile_picture')),
                ('joined_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
